language: python
python:
    - "2.7"
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install coveralls # for coverage
    - git submodule update --init --recursive

# command to run tests
script:
    - coverage run --branch --source mgen -m py.test

after_success:
    - coveralls
