:: Runs the music_generator with provided arguments

:: Variables
set PROBABILITY_FILE=C:\Users\TheGoobster\Documents\GitHub\music_generator\probabilities.cfg
set OUTPUT_FILEPATH=C:\Users\TheGoobster\Documents\GitHub\music_generator\poop
set COMPOSITION_NAME=Magic Music Composition - Generated by Alex VanTol's Code
set KEY=C

:: Other arguments
set ADAPTIVE_CHORD_TRACK_NUM_BARS=4
set GENERATE_MIDI_FILE=-midi

:: Execution
py main.py -prob "%PROBABILITY_FILE%" -k %KEY% -c "%COMPOSITION_NAME%" %GENERATE_MIDI_FILE%

pause